#pragma once

#include <limits>

/*
    This file is part of jpcsp.

    Jpcsp is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Jpcsp is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Jpcsp.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace jpcsp::Debugger
{

	using namespace jpcsp;

	class ElfHeaderInfo : public javax::swing::JFrame
	{

		/** Creates new form ElfHeaderInfo */
	public:
		virtual ~ElfHeaderInfo()
		{
			delete ELFInfoArea;
			delete jScrollPane1;
		}

		ElfHeaderInfo();
		virtual void RefreshWindow();
		/** This method is called from within the constructor to
		 * initialize the form.
		 * WARNING: Do NOT modify this code. The content of this method is
		 * always regenerated by the Form Editor.
		 */
	private:
//JAVA TO C++ CONVERTER TODO TASK: Most Java annotations will not have direct C++ equivalents:
//ORIGINAL LINE: @SuppressWarnings("unchecked") private void initComponents()
		void initComponents();

	private:
		class WindowAdapterAnonymousInnerClass : public java::awt::event::WindowAdapter
		{
		private:
			ElfHeaderInfo *outerInstance;

		public:
			virtual ~WindowAdapterAnonymousInnerClass()
			{
				delete outerInstance;
			}

			WindowAdapterAnonymousInnerClass(ElfHeaderInfo *outerInstance);

			void windowDeactivated(java::awt::event::WindowEvent *evt);
		};



private:
	void formWindowDeactivated(java::awt::event::WindowEvent *evt);


		// Variables declaration - do not modify//GEN-BEGIN:variables
		javax::swing::JTextArea *ELFInfoArea;
		javax::swing::JScrollPane *jScrollPane1;
		// End of variables declaration//GEN-END:variables

	};

}
